stages:
          - build
          - deploy

deploy-prod:
          image: node:12.18.0-alpine
          stage: deploy
          script:
            - npm i -g firebase-tools
            - npm install
            - npm i path
            - npm audit fix --force
            - npm run start
            - npm -v
          artifacts:
              paths:
                - node_modules/
